### ISSUE TITLE
Hangs at "Connecting to /dev/tty.usbmodem"

### ISSUE THREAD

**Issue by dComposer** [paulober/Pico-W-Go#39] opened 2022-12-27 02:04 UTC
## What are the steps to reproduce this issue?
1. Trying to connect to my pico using pico-w-go (on a Mac M1 Mini)

## What happens?
Terminal hangs at "Connecting to /dev/tty.usbmodem213201..."

## What were you expecting to happen?
I expect it to connect to my Pico

## Any logs, error output, etc?
* No error output, just hangs at trying to connect to my pico

## Any other comments?
I was able to use pico-w-go to discover my serial ports

## Support info

Copy this from the `Help -> Info/About -> Copy` option in Visual Studio Code:

```
Version: 1.74.2 (Universal)
Commit: e8a3071ea4344d9d48ef8a4df2c097372b0c5161
Date: 2022-12-20T10:26:09.430Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 22.1.0
Sandboxed: No
```

**Comment by paulober** [comment] 2023-01-15 20:58
Which version of Pico-W-Go and Python have you installed on you system?

**Comment by paulober** [comment] 2023-01-15 21:03
This could be due to permission erros. Some unix like operating systems do have very restricted permission on device files like the one for the serial connection to your pico. Try connection to you Pico with a diffrent serial console like minicom without sudo. If this does not that could be an indicator that it's the permission thing. Here is a description on how to solve this problem on a linux machine: [Pico-W-Go -> Wiki -> Linux](https://github.com/paulober/Pico-W-Go/wiki/Linux) mybe that helps you finding a way to get access on your machine. Unfortunately I don't have access to a macOS bases machine so i cannot give you more advice on the system part.

**Comment by dburles** [comment] 2023-01-17 22:45
I have this same issue (MacOS), it is indicating that it's connected in the status bar, however the console hangs at this message on starting vscode. I would expect it should stop the running program and land on the REPL, though this never happens.

**Comment by paulober** [comment] 2023-04-11 20:03
@dComposer @dburles Does the new version 3 of the extension resolve your issue?

**Comment by dburles** [comment] 2023-04-13 05:25
@paulober It does. Though sometimes the REPL occasionally hangs upon opening and causing the other commands (connect/disconnect, run, reset etc) to become unresponsive. Can't seem to find a reliable way to reproduce it.
<img width="814" alt="Screenshot 2023-04-13 at 3 18 51 pm" src="https://user-images.githubusercontent.com/319567/231660744-3274d4c5-dd49-4eea-981e-d95e28c9ee6c.png">

**Comment by paulober** [comment] 2023-06-14 23:05
Fixed with v3+

**Closed by paulober** 2023-06-14 23:05 UTC
Labels: bug
