### ISSUE TITLE
Connecting a Pico W doesn't trigger a vREPL

### ISSUE THREAD

**Issue by Tonyindahouse** [paulober/Pico-W-Go#60] opened 2023-04-10 20:17 UTC
## What are the steps to reproduce this issue?
1. open VSCode without a Pico W connected to computer USB or disconnect a Pico and then reconnect it.
2. connect PicoW to USB

## What happens?
Nothing happens when the Pico W is plugged in. I have to create a new vREPL manually in the Terminal window. Sometimes this works first time but usually I have to restart VSCode to get a connected vREPL.

## What were you expecting to happen?
The previous version would detect the new Pico and would create a REPL terminal linked to it automatically.

## Any logs, error output, etc?
None.

## Any other comments?
None.

## Support info
Windows 10.

Version: 1.77.1 (user setup)
Commit: b7886d7461186a5eac768481578c1d7ca80e2d21
Date: 2023-04-04T23:21:11.906Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: No

**Comment by paulober** [comment] 2023-04-10 21:40
When you open a Pico project without a Pico connected it fails to connect (obviously). If you then connect the Pico to your computer you have to run the connect command (Ctrl+Shift+P  -> "> Pico-W-Go > Connect") first, otherwise the vREPL you create manually does not have a connection to the device. 

Does this solve this issue?
I'll try to improve the UX for this kind of scenario.

**Comment by paulober** [comment] 2023-04-11 19:37
@Tonyindahouse I've taken their issue seriously, and have now re-implemented AutoConnect as a feature (with v3 patch 2). Should they have time I would be interested to know if this has fixed the problem for you, too, or if there are any problems.

**Comment by Tonyindahouse** [comment] 2023-04-11 21:34
Thanks, Paul. I'll be back home on Friday so will update and take a look.

Cheers, Tony

**Comment by bcseh202** [comment] 2023-04-14 14:19
@paulober I'm having the exact same issue, yesterday everything worked fine but now when i open vs code (with pico connected) and i click 'Run' i got the error message 'Pico vREPL not open.' and when i open it (Terminal-PicoWGo vREPL) i see nothing only the >>>. I mean i can run the program but the vREPL stays the same instead of giving me feedback like uploading or serial prints or anything, very frustrating. The program itself runs because i tested it with a simple blink example too.

**Comment by paulober** [comment] 2023-04-14 18:59
@bcseh202 If you run a script it should print the output to the vREPL but if you don't print anything with your script it only changes the Run button into Stop. And the thing with the vREPL not open message has something to to with the vscode api, because i could not manage to open a new terminal with an existing terminal profile thought the integrated command.

What would you suggest as feedback when running a script without terminal output? Or are you now not getting terminal output even if you print something?

**Comment by bcseh202** [comment] 2023-04-15 11:02
@paulober i understand, hovewer the run button doesn't change (just in function, so it still displays 'Run' but i can stop the program with it) and the vREPL only displays >>> and nothing else. In previous versions there was text indicating the board's soft and hard reset, deleting files, uploading files etc. Now they are gone for some reason.
I only suggest bringing back the feedback part of it for e.g. the commands (Soft resetting the board on COMX... of something and for the other commands. It is possible that it is just a bug that these are missing for now?)
For running a simple 'Running script/program on board COMX' and 'Script/Program stopped by user' would be great just for better feedback. :)

**Comment by paulober** [comment] 2023-04-18 16:07
@bcseh202 Thanks for the feedback. No it's not a bug as i thought with V3 that all these operations indicate their status thought a  notification like other extensions do. But i can see your concern that it can be a worse experience in some scenarios. When I have time again to work more on the project i'll consider adding something like a verbose output for command permanently or as an option.

**Comment by webdeb** [comment] 2023-06-10 16:19
@paulober sorry, if this is not the right place to ask, but its related to vREPL.
When doing a hard-reset (reboot) without running a file directly. Should't the vREPL show directly whats going on on the board? Or is the vREPL only showing what happens by running a file?

**Comment by paulober** [comment] 2023-06-19 16:10
@webdeb Your MicroPython code should not have any impact on the vREPL.

**Comment by paulober** [comment] 2023-06-19 16:13
@balazscseh The issue should be resolved with the latest update and with the next patch it will automatically open the vREPL when executing code. Can you confirm?
(and @Tonyindahouse)

**Comment by webdeb** [comment] 2023-06-19 16:25
@paulober I'll update the issue, when I am going to work on the pico project

**Closed** 2023-06-20 21:42 UTC
Labels: enhancement, v3

**Comment by NakhlaRobotics** [comment] 2023-06-25 00:33
I am trying to use MicroPython on VSCode running on a Windows 10 computer.  It always says the "Pico Disconnected" and I can't get it connected.  Thonny, howvwer, can connect with the board.  I am new to using Pico so any help is highly appreciated.

Version: 1.79.2 (user setup)
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
Date: 2023-06-14T08:57:04.379Z
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by NakhlaRobotics** [comment] 2023-06-25 00:34
Und vielen dank fur dein hilfe

**Comment by paulober** [comment] 2023-06-25 18:06
If you haven't changed any settings of the extension is should automatically connect to the pico. If you see the Pico Disconnected status bar icon in vscode (lower left hand corner) it means that the extension was activated successfully. So it could be that the application you used before hasn't freed the serial port of the Pico so the extension can't connect. To fix you issue do the normal debugging steps:

- Just open a Pico project (you configured before with Pico-W-Go configure project command) and wait if it can connect to the pico (this sometimes takes one or two seconds. If it does not connect unplug and plug the Pico back in; wait for auto-connect 
- Open the "Output" panel in vscode and select "Extension Host" in the dropdown. See if you can find any error messages or one related to pico-w-go. Now select "Pico-W-Go" in the dropdown and copy the output.
- What Python installation do you have, is it on PATH?

**Comment by PerBr-RISE** [comment] 2023-07-15 18:47
Hi Paul,

I have the same problem as NakhlaRobotics describe. 
I have a old Pico project created with the Pico-W-Go extension that worked perfectly 5 month ago but when I opened it today I get "Connection to Pico Lost" and are stuck in "Pico Disconnected" mode. I can connect to the Pico via Putty on COM3 and everything looks OK and I get ">>>" prompt after pressing return once and everything seems to work via the Putty terminal e.g. see `sys.version_info` below.

I have;
* Win 11 machine 
* with the latest VS Code (v1.79.2)
* and the latest Pico-W-Go extension (v3.2.0)
* Python version is 3.9.12 installed via a Miniconda installation - updated today
* Yes, python is in the system PATH ( PATH=C:\tools\miniconda3;C:\tools\miniconda3\Libr....  )
* MicroPython Version info from the Pico
```
>>> sys.version_info
(3, 4, 0) 
```



Looking at the "Extension Host" output there is a long stream (one new [error] approx every second) of the following;


```
2023-07-15 20:20:27.862 [error] Error: Invalid response
	at Socket.<anonymous> (c:\Users\perbr\.vscode\extensions\paulober.pico-w-go-3.2.0-win32-x64\dist\extension.cjs:1:5547)
	at Socket.emit (node:events:513:28)
	at addChunk (node:internal/streams/readable:315:12)
	at readableAddChunk (node:internal/streams/readable:289:9)
	at Readable.push (node:internal/streams/readable:228:10)
	at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
...
```

 
and the "Pico-W-Go" output looks like this;

```
2023-07-15 19:57:43.562 [info] [Activator] Connection to wrapper successfully established
2023-07-15 19:57:43.991 [error] [Activator] Pyboard exited with code 1
2023-07-15 19:58:31.262 [info] [Activator] Connection to wrapper successfully established
2023-07-15 19:58:31.351 [error] [Activator] Pyboard exited with code 1
2023-07-15 19:58:32.767 [info] [Activator] Connection to wrapper successfully established
2023-07-15 19:58:32.853 [error] [Activator] Pyboard exited with code 1
2023-07-15 19:59:04.356 [info] [Activator] Connection to wrapper successfully established
2023-07-15 19:59:04.456 [error] [Activator] Pyboard exited with code 1
2023-07-15 19:59:49.291 [info] [Activator] Connection to wrapper successfully established
2023-07-15 19:59:49.377 [error] [Activator] Pyboard exited with code 1
```

Any suggestion on what to do to fix this?

BR,
/Per

**Comment by paulober** [comment] 2023-07-15 20:41
@PerBr-RISE Thanks for providing all the useful debug information, I hope they'll enable me to track down the issue.
Here are some instruction that will help to find the root cause of the problem:
Cd into the extension:
```cmd
cd c:\Users\perbr\.vscode\extensions\paulober.pico-w-go-3.2.0-win32-x64\dist\scripts
```
now run the wrapper first with following arguments:
```
python.exe .\wrapper.py --scan-ports
```
then like so:
```
python.exe .\wrapper.py -d COM3 -b 115200
```
If the first command returned successfully and the second one is running without any output then try copying following like in your powershell and press enter:
```json
{ "command": "status" }
```
if that also worked than you can enter following to exit:
```json
{ "command": "exit" }
```

Please send me all output back so I can remote diagnose the issue.

**Comment by PerBr-RISE** [comment] 2023-07-16 21:40
Hi,
@paulober   Thanks for the quick response.  I think I found the issue.
Pyserial was not installed in the 'base' virtual environment.
I normally use dedicated venv:s in my projects and I select the project specific venv in VS Code.
In this case the current project venv has pyserial but it looks like Pico-W-Go uses the 'base' venv, or? 

Anyhow, I found the issues when I ran what you suggested and at I first I got a an error message that pyserial was missing.
I ran `pip install pyserial` to install pyserial in the 'base' venv and then ran your commands again.
Now it works and it also connects in VS code !! 


```
(base) PS C:\Users\perbr> cd c:\Users\perbr\.vscode\extensions\paulober.pico-w-go-3.2.0-win32-x64\dist\scripts
(base) PS C:\Users\perbr\.vscode\extensions\paulober.pico-w-go-3.2.0-win32-x64\dist\scripts> ls


    Directory: C:\Users\perbr\.vscode\extensions\paulober.pico-w-go-3.2.0-win32-x64\dist\scripts


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        2023-07-15     18:51                __pycache__
-a----        2023-07-15     18:06           3382 mpyFunctions.py
-a----        2023-07-15     18:06          35334 pyboard.py
-a----        2023-07-15     18:06           1679 utils.py
-a----        2023-07-15     18:06          35954 wrapper.py


(base) PS C:\Users\perbr\.vscode\extensions\paulober.pico-w-go-3.2.0-win32-x64\dist\scripts> python.exe .\wrapper.py --scan-ports
!!ImportError!!
Please install pyserial

(base) PS C:\Users\perbr\.vscode\extensions\paulober.pico-w-go-3.2.0-win32-x64\dist\scripts> pip install pyserial
Collecting pyserial
  Using cached pyserial-3.5-py2.py3-none-any.whl (90 kB)
Installing collected packages: pyserial
Successfully installed pyserial-3.5

(base) PS C:\Users\perbr\.vscode\extensions\paulober.pico-w-go-3.2.0-win32-x64\dist\scripts> python.exe .\wrapper.py --scan-ports
COM3
!!EOO!!

(base) PS C:\Users\perbr\.vscode\extensions\paulober.pico-w-go-3.2.0-win32-x64\dist\scripts> python.exe .\wrapper.py -d COM3 -b 115200
{ "command": "status" }
!!EOO!!
{ "command": "exit" }
(base) PS C:\Users\perbr\.vscode\extensions\paulober.pico-w-go-3.2.0-win32-x64\dist\scripts>
```

Interesting is that in VS Code I can not recall ever seeing any error indicating that `pyserial` was missing.
And as I know that `pyserial` is a requirement I checked that it was installed but only in my project environment. :-)
 
Thanks,
/Per

**Comment by NakhlaRobotics** [comment] 2023-07-17 00:46
Gentlemen,

Thank you very much for your help.  Unfortunately, i am still not able to
fix the issue.  I followed the instructions but it gives me a Python
error.  Here is the error I get


C:\Users\Admin\.vscode\extensions\paulober.pico-w-go-3.2.0-win32-x64\dist\scripts>python.exe
.\wrapper.py --scan-ports
'import site' failed; use -v for traceback
  File ".\wrapper.py", line 19
    SUPPORTED_USB_PIDS: list[int] = [
                      ^
SyntaxError: invalid syntax

C:\Users\Admin\.vscode\extensions\paulober.pico-w-go-3.2.0-win32-x64\dist\scripts>

I ran it with -v and I get this trace

C:\Users\Admin\.vscode\extensions\paulober.pico-w-go-3.2.0-win32-x64\dist\scripts>python.exe
-v .\wrapper.py --scan-ports
# installing zipimport hook
import zipimport # builtin
# installed zipimport hook
'import site' failed; traceback:
ImportError: No module named site
Python 2.6.6 (r266:84297, Aug 24 2010, 18:46:32) [MSC v.1500 32 bit
(Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
  File ".\wrapper.py", line 19
    SUPPORTED_USB_PIDS: list[int] = [
                      ^
SyntaxError: invalid syntax


Please note it refers to Python 2.6.6 although I only have Python 3.11.3 on
my machine

C:\Users\Admin\.vscode\extensions\paulober.pico-w-go-3.2.0-win32-x64\dist\scripts>py
--version
Python 3.11.3

C:\Users\Admin\.vscode\extensions\paulober.pico-w-go-3.2.0-win32-x64\dist\scripts>

Is that an issue with the installation?

Thank you
Said Nakhla
NakhlaRobotics

**Comment by paulober** [comment] 2023-07-17 10:02
@PerBr-RISE Strange. I would like to solve this issue for all within the extension. 
I'm glad that is was so "easy" for you to solve it but it would be interesting why it needed that.
The extension installs pyserial if not available with following command: `python -m pip install --upgrade pyserial`
And it validates the install with following command: `python -m pip show pyserial` and check if the output contains `Name: pyserial`

**Comment by paulober** [comment] 2023-07-17 10:09
@NakhlaRobotics The syntax error you're getting is cause by this syntax `: list[int] =` introduces with Python 3.9 and you normally get this error with a version prior to 3.9. When you check you version thought `py --version` you were using the Windows pylauncher (`py.exe`). But when you run the script you use `python.exe` so I assume you have an old python 2.6.6 installation laying somewhere around. That must be because it also knows all the details about this installation: `(r266:84297, Aug 24 2010, 18:46:32) [MSC v.1500 32 bit
(Intel)] on win32`. 

Try `python.exe -V` and `where.exe python.exe`. The first command should return 2.6.6 and the second one shows you all paths to python executables in your PATH.

**Comment by PerBr-RISE** [comment] 2023-07-20 11:32
@paulober I did some "spring cleaning" of me laptop and removed some old Python 2.x installation a few month ago. Maybe the one that Pico-W-Go used was removed.
I did not reinstall Pico-W-Go after the "spring cleaning", that might have solved the issue.
